### ISSUE TITLE
Npm or Yarn?

### ISSUE THREAD

**Issue by ClydeFrog04** [Laarzae-Studios/Laarzae-Studios-React#6]
Our readme says to use npm install to work on this project but we have a yarn.lock file- we might run into issues that are hard to debug down the road using both!

**Comment by HeyMichelle** [comment]
NPM only @ngwatso can we remove that? We want to keep it npm. @ClydeFrog04 i think it’s because CRA has it included in initial start-up

**Comment by ClydeFrog04** [comment]
for sure that's why. For future reference for everyone, cra has a --use-npm flag which will use npm instead of yarn. Example: npx create-react-app my-app --use-npm
https://create-react-app.dev/docs/getting-started/
I'll get this fixed!

**Comment by ClydeFrog04** [comment]
Fixed by #7
